"use client"

import { useCallback, type FormEvent } from "react"

import { openUrlOnHost } from "./host-bridge"

export type PrechatFields = {
  name: string
  email: string
  phone: string
  inquiryType: string
  message: string
}

type PrechatFormProps = {
  name: string
  privacyUrl: string
  onSubmit: (fields: PrechatFields) => void
}

const PRIVACY =
  "Some replies are generated by an assistant. Do not send Social Security numbers, driver's-license numbers, license plates, or medical information."

const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
const FIELD =
  "rounded-[8px] border border-line bg-paper px-3 py-2.5 text-base font-normal outline-none transition-colors focus-visible:border-steel focus-visible:ring-2 focus-visible:ring-steel"

const focusNamed = (form: HTMLFormElement, name: string) => {
  const field = form.elements.namedItem(name)
  if (field instanceof HTMLInputElement || field instanceof HTMLTextAreaElement) {
    field.focus()
  }
}

const readFields = (form: HTMLFormElement): PrechatFields => {
  const data = new FormData(form)
  return {
    name: String(data.get("name") ?? "").trim(),
    email: String(data.get("email") ?? ""),
    phone: String(data.get("phone") ?? ""),
    inquiryType: String(data.get("inquiryType") ?? "other"),
    message: String(data.get("message") ?? ""),
  }
}

export const PrechatForm = ({ name, privacyUrl, onSubmit }: PrechatFormProps) => {
  const displayName = name
    .replace(/\bdemo\b/gi, "")
    .replace(/\s{2,}/g, " ")
    .trim()
  const handleSubmit = useCallback(
    (event: FormEvent<HTMLFormElement>) => {
      event.preventDefault()
      const form = event.currentTarget
      const fields = readFields(form)
      if (fields.name === "") {
        focusNamed(form, "name")
        return
      }
      if (!EMAIL_PATTERN.test(fields.email)) {
        focusNamed(form, "email")
        return
      }
      onSubmit(fields)
    },
    [onSubmit],
  )
  const handlePrivacy = useCallback(() => {
    openUrlOnHost(privacyUrl)
  }, [privacyUrl])

  return (
    <form
      onSubmit={handleSubmit}
      noValidate
      className="widget-enter bg-paper flex min-h-0 flex-1 flex-col"
    >
      <div className="flex min-h-0 flex-1 flex-col gap-4 overflow-y-auto bg-[#FAFBFD] px-5 py-6">
        <div>
          <p className="text-steel text-[10px] font-extrabold tracking-[0.14em] uppercase">
            Start a conversation
          </p>
          {displayName ? (
            <h2 className="text-navy mt-1.5 text-lg font-extrabold tracking-[-0.035em]">
              {displayName}
            </h2>
          ) : null}
          <p className="text-mute mt-1 text-xs leading-5">Tell us how we can help.</p>
        </div>
        <Field label="Full name" name="name" autoComplete="name" required />
        <Field
          label="Email"
          name="email"
          type="email"
          autoComplete="email"
          required
          spellCheck={false}
        />
        <Field label="Phone" name="phone" type="tel" autoComplete="tel" />
        <InquirySelect />
        <label className="text-ink flex flex-col gap-1 text-sm font-medium">
          Message
          <textarea name="message" rows={3} className={FIELD} />
        </label>
        <p className="border-line text-mute border-l-ember bg-paper rounded-[8px] border-l-2 px-3 py-2.5 text-xs leading-5">
          {PRIVACY}
        </p>
        <button
          type="button"
          className="text-steel focus-visible:ring-steel w-fit cursor-pointer text-xs font-bold underline-offset-4 hover:underline focus-visible:ring-2"
          onClick={handlePrivacy}
        >
          Privacy notice
        </button>
      </div>
      <div className="border-line bg-paper shrink-0 border-t px-5 py-4">
        <button
          type="submit"
          className="bg-steel text-paper focus-visible:ring-steel hover:bg-navy min-h-11 w-full rounded-[8px] px-4 py-2.5 text-sm font-bold focus-visible:ring-2 focus-visible:outline-none"
        >
          Start the chat
        </button>
      </div>
    </form>
  )
}

type FieldProps = {
  label: string
  name: string
  type?: string
  autoComplete: string
  required?: boolean
  spellCheck?: boolean
}

const Field = ({ label, name, type = "text", autoComplete, required, spellCheck }: FieldProps) => {
  return (
    <label className="text-ink flex flex-col gap-1 text-sm font-medium">
      {label}
      <input
        type={type}
        name={name}
        autoComplete={autoComplete}
        required={required}
        spellCheck={spellCheck}
        className={FIELD}
      />
    </label>
  )
}

const INQUIRY_ITEMS = [
  { label: "Sales", value: "sales" },
  { label: "Results timing", value: "results" },
  { label: "Applicant portal", value: "portal" },
  { label: "Compliance", value: "compliance" },
  { label: "Other", value: "other" },
]

const InquirySelect = () => {
  return (
    <label className="text-ink flex flex-col gap-1 text-sm font-medium" htmlFor="inquiry-type">
      Inquiry type
      <select
        id="inquiry-type"
        name="inquiryType"
        defaultValue="other"
        className="border-line bg-paper text-ink focus-visible:border-steel focus-visible:ring-steel h-11 w-full cursor-pointer rounded-[8px] border px-3 text-base font-normal outline-none focus-visible:ring-2"
      >
        {INQUIRY_ITEMS.map((item) => (
          <option key={item.value} value={item.value}>
            {item.label}
          </option>
        ))}
      </select>
    </label>
  )
}
