"use client"

import { useCallback, useState, type FocusEvent, type FormEvent } from "react"

import { Button } from "@/components/ui/button"
import { FieldError } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { emailError, phoneError, requiredError } from "@/lib/validation"

import { openUrlOnHost } from "./host-bridge"

export type PrechatFields = {
  name: string
  email: string
  phone: string
  inquiryType: string
  message: string
}

type PrechatFormProps = {
  name: string
  privacyUrl: string
  onSubmit: (fields: PrechatFields) => void
}

const PRIVACY =
  "Some replies are generated by an assistant. Do not send Social Security numbers, driver's-license numbers, license plates, or medical information."

const FIELD =
  "h-11 rounded-[8px] border border-line bg-paper px-3 py-2.5 text-base font-normal outline-none transition-colors focus-visible:border-steel focus-visible:ring-2 focus-visible:ring-steel"

const ICE_BUTTON =
  "border-steel/15 bg-ice-2 text-navy hover:!bg-[#e6eefc] hover:!text-navy focus-visible:ring-steel/30 min-h-11 w-full border px-4 text-sm font-bold leading-none shadow-[0_8px_20px_rgba(36,86,160,0.12)] focus-visible:ring-4"

const focusNamed = (form: HTMLFormElement, name: string) => {
  const field = form.elements.namedItem(name)
  if (field instanceof HTMLInputElement || field instanceof HTMLTextAreaElement) {
    field.focus()
  }
}

const readFields = (form: HTMLFormElement): PrechatFields => {
  const data = new FormData(form)
  return {
    name: String(data.get("name") ?? "").trim(),
    email: String(data.get("email") ?? ""),
    phone: String(data.get("phone") ?? ""),
    inquiryType: String(data.get("inquiryType") ?? "other"),
    message: String(data.get("message") ?? ""),
  }
}

export const PrechatForm = ({ name, privacyUrl, onSubmit }: PrechatFormProps) => {
  const [errors, setErrors] = useState<Record<string, string>>({})
  const displayName = name
    .replace(/\bdemo\b/gi, "")
    .replace(/\s{2,}/g, " ")
    .trim()
  const handleSubmit = useCallback(
    (event: FormEvent<HTMLFormElement>) => {
      event.preventDefault()
      const form = event.currentTarget
      const fields = readFields(form)
      const nextErrors = {
        name: requiredError("Full name", fields.name),
        email: emailError(fields.email),
        phone: phoneError(fields.phone),
      }
      const visibleErrors = Object.fromEntries(
        Object.entries(nextErrors).filter((entry): entry is [string, string] => entry[1] !== null),
      )
      setErrors(visibleErrors)
      if (visibleErrors.name) {
        focusNamed(form, "name")
        return
      }
      if (visibleErrors.email) {
        focusNamed(form, "email")
        return
      }
      if (visibleErrors.phone) {
        focusNamed(form, "phone")
        return
      }
      onSubmit(fields)
    },
    [onSubmit],
  )
  const handleBlur = useCallback((event: FocusEvent<HTMLInputElement>) => {
    const { name: fieldName, value } = event.currentTarget
    const error =
      fieldName === "name"
        ? requiredError("Full name", value)
        : fieldName === "phone"
          ? phoneError(value)
          : emailError(value)
    setErrors((current) => {
      if (error === null) {
        const next = { ...current }
        delete next[fieldName]
        return next
      }
      return { ...current, [fieldName]: error }
    })
  }, [])
  const handlePrivacy = useCallback(() => {
    openUrlOnHost(privacyUrl)
  }, [privacyUrl])

  return (
    <form
      onSubmit={handleSubmit}
      noValidate
      className="widget-enter flex min-h-0 flex-1 flex-col bg-transparent"
    >
      <PrechatFields
        displayName={displayName}
        errors={errors}
        onBlur={handleBlur}
        onPrivacy={handlePrivacy}
      />
    </form>
  )
}

const PrechatFields = ({
  displayName,
  errors,
  onBlur,
  onPrivacy,
}: {
  displayName: string
  errors: Record<string, string>
  onBlur: (event: FocusEvent<HTMLInputElement>) => void
  onPrivacy: () => void
}) => (
  <>
    <div className="flex min-h-0 flex-1 flex-col gap-4 overflow-y-auto px-5 py-4">
      <div>
        <p className="text-steel text-[10px] font-semibold tracking-[0.2em] uppercase">
          Start a conversation
        </p>
        {displayName ? <h2 className="text-navy heading mt-1.5 text-lg">{displayName}</h2> : null}
        <p className="text-mute mt-1 text-xs leading-5">Tell us how we can help.</p>
      </div>
      <Field
        label="Full name"
        name="name"
        autoComplete="name"
        required
        error={errors.name}
        onBlur={onBlur}
      />
      <Field
        label="Email"
        name="email"
        type="email"
        autoComplete="email"
        required
        spellCheck={false}
        error={errors.email}
        onBlur={onBlur}
      />
      <Field
        label="Phone"
        name="phone"
        type="tel"
        autoComplete="tel"
        error={errors.phone}
        onBlur={onBlur}
      />
      <InquirySelect />
      <label className="text-ink flex flex-col gap-1 text-sm font-medium" htmlFor="prechat-message">
        Message
        <Textarea id="prechat-message" name="message" rows={3} maxLength={2000} className={FIELD} />
      </label>
      <p className="text-mute rounded-[18px] bg-white/70 px-3 py-2.5 text-xs leading-5 shadow-[0_6px_18px_rgba(13,31,58,0.06)] backdrop-blur-xl">
        {PRIVACY}
      </p>
      <Button
        type="button"
        variant="link"
        size="sm"
        className="text-steel focus-visible:ring-steel w-fit cursor-pointer text-xs font-bold focus-visible:ring-2"
        onClick={onPrivacy}
      >
        Privacy notice
      </Button>
    </div>
    <div className="shrink-0 bg-transparent px-3 pt-2 pb-3">
      <Button type="submit" variant="secondary" size="lg" className={ICE_BUTTON}>
        Start the chat
      </Button>
    </div>
  </>
)

type FieldProps = {
  label: string
  name: string
  type?: string
  autoComplete: string
  required?: boolean
  spellCheck?: boolean
  error?: string
  onBlur?: (event: FocusEvent<HTMLInputElement>) => void
}

const Field = ({
  label,
  name,
  type = "text",
  autoComplete,
  required,
  spellCheck,
  error,
  onBlur,
}: FieldProps) => {
  const errorId = `${name}-error`
  return (
    <div className="text-ink flex flex-col gap-1 text-sm font-medium">
      <label htmlFor={name}>{label}</label>
      <Input
        id={name}
        type={type}
        name={name}
        autoComplete={autoComplete}
        required={required}
        spellCheck={spellCheck}
        className={FIELD}
        aria-invalid={error ? "true" : undefined}
        aria-describedby={errorId}
        onBlur={onBlur}
      />
      <FieldError id={errorId}>{error}</FieldError>
    </div>
  )
}

const INQUIRY_ITEMS = [
  { label: "Sales", value: "sales" },
  { label: "Results timing", value: "results" },
  { label: "Applicant portal", value: "portal" },
  { label: "Compliance", value: "compliance" },
  { label: "Other", value: "other" },
]

const INQUIRY_LABELS = Object.fromEntries(INQUIRY_ITEMS.map((item) => [item.value, item.label]))

const InquirySelect = () => {
  const [value, setValue] = useState("other")
  const handleValueChange = useCallback((next: string | null) => {
    if (typeof next === "string") {
      setValue(next)
    }
  }, [])
  return (
    <div className="text-ink flex flex-col gap-1 text-sm font-medium">
      <label htmlFor="inquiry-type">Inquiry type</label>
      <input type="hidden" name="inquiryType" value={value} />
      <Select value={value} onValueChange={handleValueChange} items={INQUIRY_LABELS}>
        <SelectTrigger
          id="inquiry-type"
          className="border-line bg-paper focus-visible:border-steel focus-visible:ring-steel h-11 w-full rounded-[8px] px-3 text-base font-normal"
        >
          <SelectValue />
        </SelectTrigger>
        <SelectContent align="start" alignItemWithTrigger={false}>
          <SelectGroup>
            {INQUIRY_ITEMS.map((item) => (
              <SelectItem key={item.value} value={item.value}>
                {item.label}
              </SelectItem>
            ))}
          </SelectGroup>
        </SelectContent>
      </Select>
    </div>
  )
}
