"""chat_core

Revision ID: 11be8f4f569e
Revises: 001_users_refresh
Create Date: 2026-09-09 12:31:15.429287
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "11be8f4f569e"
down_revision: str | Sequence[str] | None = "001_users_refresh"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sites",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("public_key", sa.String(), nullable=False),
        sa.Column("allowed_origins", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("greeting", sa.String(), nullable=False),
        sa.Column("privacy_url", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
        sa.UniqueConstraint("public_key"),
    )
    op.create_table(
        "canned_replies",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("shortcut", sa.String(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("site_id", "shortcut", name="uq_canned_replies_site_shortcut"),
    )
    op.create_table(
        "kb_articles",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "search_document",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('english', coalesce(title,'') || ' ' || coalesce(body,''))",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("site_id", "title", name="uq_kb_articles_site_title"),
    )
    op.create_table(
        "visitors",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("resume_token_hash", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("geo_country", sa.String(), nullable=True),
        sa.Column("geo_region", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "site_id", name="uq_visitors_id_site"),
        sa.UniqueConstraint("site_id", "resume_token_hash", name="uq_visitors_site_resume"),
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("visitor_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("active_generation_id", sa.Uuid(), nullable=True),
        sa.Column("prechat_submission_id", sa.Uuid(), nullable=True),
        sa.Column("prechat_payload_hash", sa.String(), nullable=True),
        sa.Column("inquiry_type", sa.String(), nullable=True),
        sa.Column("intent", sa.String(), nullable=True),
        sa.Column("fallback_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("page_url", sa.String(), nullable=True),
        sa.Column("page_title", sa.String(), nullable=True),
        sa.Column("referrer", sa.String(), nullable=True),
        sa.Column("assigned_agent_id", sa.Uuid(), nullable=True),
        sa.Column(
            "last_message_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(active_generation_id IS NULL) OR (state = 'bot')",
            name="ck_conversations_generation_bot_only",
        ),
        sa.CheckConstraint(
            "(state = 'human' AND assigned_agent_id IS NOT NULL) OR (state IN ('prechat','bot','queued') AND assigned_agent_id IS NULL) OR (state = 'closed')",
            name="ck_conversations_assignment",
        ),
        sa.CheckConstraint(
            "inquiry_type IS NULL OR inquiry_type IN ('sales','results','portal','compliance','other')",
            name="ck_conversations_inquiry",
        ),
        sa.CheckConstraint(
            "intent IS NULL OR intent IN ('pricing','turnaround','dot','fcra','portal','escalate','other')",
            name="ck_conversations_intent",
        ),
        sa.CheckConstraint(
            "state IN ('prechat','bot','queued','human','closed')", name="ck_conversations_state"
        ),
        sa.CheckConstraint("fallback_count >= 0", name="ck_conversations_fallback"),
        sa.ForeignKeyConstraint(
            ["assigned_agent_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
        ),
        sa.ForeignKeyConstraint(
            ["visitor_id", "site_id"],
            ["visitors.id", "visitors.site_id"],
            name="fk_conversations_visitor_site",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_conversations_site_last_message",
        "conversations",
        ["site_id", "last_message_at"],
        unique=False,
    )
    op.create_index(
        "ix_conversations_state_last_message",
        "conversations",
        ["state", "last_message_at"],
        unique=False,
    )
    op.create_index(
        "uq_conversations_open_visitor",
        "conversations",
        ["visitor_id"],
        unique=True,
        postgresql_where=sa.text("state <> 'closed'"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("client_message_id", sa.Uuid(), nullable=True),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("author_user_id", sa.Uuid(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("source_article_ids", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(role = 'agent' AND author_user_id IS NOT NULL) OR (role <> 'agent' AND author_user_id IS NULL)",
            name="ck_messages_author",
        ),
        sa.CheckConstraint(
            "(role = 'bot' AND source_article_ids IS NOT NULL AND cardinality(source_article_ids) > 0) OR (role <> 'bot' AND (source_article_ids IS NULL))",
            name="ck_messages_sources",
        ),
        sa.CheckConstraint(
            "(role IN ('visitor','agent') AND client_message_id IS NOT NULL) OR (role IN ('bot','system') AND client_message_id IS NULL)",
            name="ck_messages_client_id",
        ),
        sa.CheckConstraint("role IN ('visitor','bot','agent','system')", name="ck_messages_role"),
        sa.ForeignKeyConstraint(
            ["author_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_messages_conversation_id", "messages", ["conversation_id", "id"], unique=False
    )
    op.create_index(
        "uq_messages_client_id",
        "messages",
        ["conversation_id", "client_message_id"],
        unique=True,
        postgresql_where=sa.text("client_message_id IS NOT NULL"),
    )
    op.create_index(
        "ix_kb_articles_search_document",
        "kb_articles",
        ["search_document"],
        postgresql_using="gin",
    )
    op.create_check_constraint(
        "ck_conversations_prechat_pair",
        "conversations",
        "(prechat_submission_id IS NULL AND prechat_payload_hash IS NULL) OR "
        "(prechat_submission_id IS NOT NULL AND prechat_payload_hash IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint("ck_conversations_prechat_pair", "conversations", type_="check")
    op.drop_index("ix_kb_articles_search_document", table_name="kb_articles")
    op.drop_index(
        "uq_messages_client_id",
        table_name="messages",
        postgresql_where=sa.text("client_message_id IS NOT NULL"),
    )
    op.drop_index("ix_messages_conversation_id", table_name="messages")
    op.drop_table("messages")
    op.drop_index(
        "uq_conversations_open_visitor",
        table_name="conversations",
        postgresql_where=sa.text("state <> 'closed'"),
    )
    op.drop_index("ix_conversations_state_last_message", table_name="conversations")
    op.drop_index("ix_conversations_site_last_message", table_name="conversations")
    op.drop_table("conversations")
    op.drop_table("visitors")
    op.drop_table("kb_articles")
    op.drop_table("canned_replies")
    op.drop_table("sites")
